language: node_js

node_js:
  - 10

script:
  - node ci.js

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install: yarn install --frozen-lockfile

cache:
  yarn: true
  directories:
    - node_modules
